<?php

/**
 * Implementation of hook_menu().
 */
function reJoin_menu(){
    $menu['project/%/manage/settings/join'] = array(
        'title arguments'   => array(1),
	'title callback'    => 'project_title_callback',
        'description'       => t('Admin join settings for project'),
        'page callback'     => 'project_manage_settings_join_callback',
        'page arguments'    => array(1),
	'access callback'   => 'manage_project_access',
        'access arguments'  => array(1),
        'file'              => 'includes/settings.pages.inc',
    );
    return $menu;
}