<?php

/**
 * Implementation of hook_menu().
 */
function reProjectMessage_menu(){
    $menu['project/%/manage/message'] = array(
        'title arguments'   => array(1),
	'title callback'    => 'project_title_callback',
        'description'       => t('Message sending'),
        'page callback'     => 'project_manage_message_email_callback',
        'page arguments'    => array(1),
	'access callback'   => 'manage_project_access',
        'access arguments'  => array(1),
        'file'              => 'includes/manage.email.pages.inc',  
    );
    $menu['project/%/manage/message/email'] = array(
        'title arguments'   => array(1),
	'title callback'    => 'project_title_callback',
        'description'       => t('Message sending'),
        'page callback'     => 'project_manage_message_email_callback',
        'page arguments'    => array(1),
	'access callback'   => 'manage_project_access',
        'access arguments'  => array(1),
        'file'              => 'includes/manage.email.pages.inc',  
    );
    $menu['project/%/manage/message/sms'] = array(
        'title arguments'   => array(1),
	'title callback'    => 'project_title_callback',
        'description'       => t('Message sending'),
        'page callback'     => 'project_manage_message_sms_callback',
        'page arguments'    => array(1),
	'access callback'   => 'manage_project_access',
        'access arguments'  => array(1),
        'file'              => 'includes/manage.sms.pages.inc',  
    );
    return $menu;
}

/**
 * Implements hook_project_manage_navigation().
 */
function reProjectMessage_project_manage_navigation($project){
    //return manage navigation menus
    $navigation[] = array(
        'title' => 'Send message',
        'url'   => 'project/'.$project->path.'/manage/message',
        'weight'=> 1,
    );
    return $navigation;
}

/**
 * Implements hook_theme().
 */
function reProjectMessage_theme(){
    return array(
	'project_person_list_div' => array(
	    'template' => 'personlist.block',
	    'arguments' => array(
		'list' => NULL,
                'type' => 'mail',
	    ),
	),
    );
}