<?php

/**
 * @file
 * Definde reseache project structure and model
 */

define('REPROJECT_MODULE_NAME','reProject');

/**
 * Implementation of hook_help().
 */
function reProject_help(){
    switch ($path) {
        case 'admin/settings/reProject':
            return t('Definde reseache project structure and model');
        case 'admin/help#reProject':
            return t('Definde reseache project structure and model');
    }
}

/**
 * Implementation of hook_menu().
 */
function reProject_menu(){
    $menu['projects/new'] = array(
        'title'             => t('Create new project'),
        'description'       => t('The page to create a new research project'),
        'page callback'     => 'projects_new_callback',
        'access arguments'  => array('create research project'),
        'file'              => 'includes/project.pages.inc',
        'type'              => MENU_NORMAL_ITEM,
    );
    $menu['projects/list'] = array(
        'title'             => t('Projects'),
        'description'       => t('List all projects'),
        'page callback'     => 'projects_list_callback',
        'access arguments'  => array('access content'),
        'file'              => 'includes/project.pages.inc',
        'type'              => MENU_NORMAL_ITEM, 
    );
    return $menu;
}

/**
 * Implementation of hook_perm().
 */
function reProject_perm(){
    return array(
        'create research project',
        'edit any research project',
        'delete research project',
    );
}

/**
 * Load project object
 * @param
 *   index, index of project(can be id or path)
 * @param
 *   type, the type of index('id' or 'path', default is 'path')
 */
function load_project($index,$type='path'){
    switch($type){
        case 'id':
            $sql = 'SELECT id, creator, name, url, path, description, created, changed FROM {research_projects} WHERE id=%d';
            return db_fetch_object(db_query($sql, $index));
        case 'path':
            $sql = "SELECT id, creator, name, url, path, description, created, changed FROM {research_projects} WHERE path='%s'";
            return db_fetch_object(db_query($sql, $index));
        default:
            return FALSE;
    }
}


/**
 * Log operation
 * @param
 *   $project_id, the id of project
 * @param
 *   $type , operating object, can be 'information','messeage', 'user', 'page'....
 * @param
 *   $content, detail description
 * @param
 *   $link, the link of the page operation happened
 * @param
 *   $module, the module call log_operation function
 */
function log_operation($project_id, $type, $content, $link, $module){
    global $user;
    $ip = $_SERVER["REMOTE_ADDR"];
    $sql = "INSERT INTO {research_projects_operation_logs} (project,operator,type,ip,content,link,module,time) VALUES(%d,%d,'%s','%s','%s','%s','%s',NOW())";
    db_query($sql, $project_id, $user->id, $type, $ip, $content, $link, $module);
}

/**
 * Save project info to table {research_projects}
 * @param
 *   $project, object of research_projects
 */
function _research_projects_save($project){
    
    $name = (string)$project->name;
    $url = isset($project->url)?(string)$project->url:'';
    $path = (string)$project->path;
    $introduction = (string)$project->introduction;
    
    if(isset($project->id) && $project->id>0){
        //update record
        $sql = "UPDATE {research_projects} SET name='%s', url='%s', path='%s', introduction='%s', changed=NOW() WHERE id=%d";
        return db_query($sql, $name, $url, $path, $introduction, $project->id);
        
    }else{
        $creator = (int)$project->creator;
        //insert new
        $sql = "INSERT INTO {research_projects} (name, creator, url, path, introduction, created, changed) VALUES('%s','%d','%s','%s','%s',NOW(),NOW())";
        return db_query($sql, $name, $creator, $url, $path, $introduction, $project->id);
    }
}
/**
 * Delect record in {research_projects}
 */
function _research_projects_delete($id){
    $sql = 'DELECT FROM {research_projects} WHERE id=%d';
    return db_query($sql, $id);
}

