<?php

/**
 * Implementation of hook_menu().
 */
function ProjectLogs_menu(){
    $menu['project/%/manage/logs'] = array(
        'title arguments'   => array(1),
	'title callback'    => 'project_title_callback',
        'description'       => t('Report logs of operations in the project.'),
        'page callback'     => 'project_manage_logs_callback',
        'page arguments'    => array(1),
	'access callback'   => 'manage_project_access',
        'access arguments'  => array(1),
        'type'              => MENU_CALLBACK, 
    );
    $menu['project/%/manage/logs/%'] = array(
        'title arguments'   => array(1),
	'title callback'    => 'project_title_callback',
        'description'       => t('Display the detail of a log.'),
        'page callback'     => 'project_manage_log_display_callback',
        'page arguments'    => array(1, 4),
	'access callback'   => 'manage_project_access',
        'access arguments'  => array(1),
        'type'              => MENU_CALLBACK, 
    );
    
    return $menu;
}

/**
 * Implementation of hook_project_manage_navigation().
 */
function ProjectLogs_project_manage_navigation($project){
    
    $navigation['manage']['sub_items']['logs_page'] = array(
        'title' => 'Action Logs',
        'url'   => generate_project_url($project->path).'/manage/logs',
        'weight'=> 9,
    );
    return $navigation;
}

/**
 * Menu callback for project/%/manage/logs
 */
function project_manage_logs_callback($path){
    $project = prepare_project_manage_page($path);
    $project->subtitle = 'Operating Track';
    
    $header = array(
        'Type','Operator', 'Message', 'Log Time',    
    );
    $rows = array();
    
    $sql = 'SELECT id, type, uid, name, content, time FROM {research_projects_operation_logs}, {users} '.
              'WHERE project='.$project->id.' AND uid=operator ORDER by time DESC';
    $res = pager_query($sql, 3);
    while($r = db_fetch_object($res)){
        $rows[] = array(
            $r->type,
            l($r->name,'user/'.$r->uid),
            $r->content. ' ('.l('More',generate_project_url($path).'/manage/logs/'.$r->id).')',
            $r->time,
        );
    }
    
    $content.= theme_table($header, $rows);
    $content.= theme_pager();
    $project->right_part = $content;    
    return theme('project_manage_page',$project);
}

/**
 * Menu callback for project/%/manage/logs/%
 */
function project_manage_log_display_callback($path, $lid){
    $project = prepare_project_manage_page($path);
    $project->subtitle = 'Operating Track';
    
    $sql = 'SELECT id, type, uid, name, content, ip, link, time FROM {research_projects_operation_logs}, {users} '.
              'WHERE id=%d AND project=%d AND uid=operator';
    $res = db_query($sql, $lid, $project->id);
    if($r = db_fetch_object($res)){
        $content.= '<dl>'
                        ."<dt>Type</dt><dd>{$r->type}</dd>"
                        ."<dt>Operator</dt><dd>".l($r->name, 'user/'.$r->uid)."</dd>";
        if(!empty($r->link)){
            $content.="<dt>Link</dt><dd>".l($r->link, $r->link)."</dd>";
        }
        $content.= "<dt>Content</dt><dd>{$r->content}</dd>"
                        ."<dt>IP address</dt><dd>{$r->ip}</dd>"
                        ."<dt>Time</dt><dd>{$r->time}</dd>"
                        .'</dl>';
    }
    $project->right_part = $content;    
    return theme('project_manage_page',$project);
}
