<?php

/**
 * @file
 * Provide functions for manage project user
 */
define('PROJECT_NORMAL_USER', 'normal');
define('PROJECT_RESEARCHER', 'researcher');

/**
 * Implementation of hook_menu().
 */
function reProjectUser_menu(){

    $menu['project/%/termofuse'] = array(
        'title'             => t('Term of use'),
        'description'       => t('Display the term of use page for project'),
        'page callback'     => 'project_termofuse_callback',
        'page arguments'    => array(1, 3),
        'access arguments'  => array('access content'),
        'file'              => 'includes/join.guide.pages.inc',
        'type'              => MENU_CALLBACK,
    );
    
    $menu['project/%/manage/contents/termofuse'] = array(
        'title'             => t('Edit term of use'),
        'page callback'     => 'project_manage_content_termofuse_callback',
        'page arguments'    => array(1),
        'access arguments'  => array('access content'),
        'file'              => 'includes/manage.contents.pages.inc',
        'type'              => MENU_CALLBACK,
    );
    
    return $menu;
}

/**
 * Implements hook_theme().
 */
function reProjectUser_theme(){
    return array(
	'project_termofuse_page' => array(
	    'template' => 'templates/termofuse.page',
	    'arguments' => array(
		'project' => NULL,
	    ),
	),
    );
}

/**
 * add user to the project
 */
function add_user_to_project($pid, $uid, $role=PROJECT_NORMAL_USER){
    //check if user already in project
    $check = 'SELECT COUNT(*) FROM {research_projects_persons_list} WHERE project=%d AND user=%d AND role="%s"';
    if(db_result(db_query($check, $pid, $uid, $role))>0){
        //insert new
        $insert = 'INSERT INTO {research_projects_persons_list}(project, user, role, created, changed) VALUES(%d, %d, "%s", NOW(), NOW())';
        return db_query($insert, $pid, $uid, $role);
    }
    return FALSE;
}

/**
 * load term of use node
 */
function load_term_of_use_node($project){
    //get term of use node
    $sql = 'SELECT node FROM {research_projects_contents} WHERE project=%d AND type="termofuse" ORDER BY created DESC LIMIT 1 ';
    $nid = db_result(db_query($sql, $project->id));
    if($nid>0){
        return node_load($nid);
    }else{
        //create new term of use page
        $node = new stdClass;
        $node->title = 'Term of use';
        $node->body = '<a href="'.url('project/'.$project->path.'/manage/contents/termofuse').'" class="edit-link">Click here to first edit.</a>';
        $node->type = 'projectcontent';
        node_save($node);
        project_add_content($pid, $node->nid, 'termofuse', FALSE);
        return $node;
    }
}
