<?php

/**
 * @file
 * Provide message templates management for for research project
 */

/**
 * Implementation of hook_menu().
 */
function ProjectMessageTemplate_menu(){
    $menu['project/%/manage/message/templates'] = array(
        'title'             => t('Message templates'),
        'description'       => t('The display the list of message templates'),
        'page callback'     => 'project_manage_message_templates_callback',
        'page arguments'    => array(1),
        'access arguments'  => array('create research project'),
        'type'              => MENU_CALLBACK,
    );
    $menu['project/%/manage/message/templates/add'] = array(
        'title'             => t('Add message template'),
        'description'       => t('Add new message template'),
        'page callback'     => 'project_manage_message_templates_add_callback',
        'page arguments'    => array(1),
        'access arguments'  => array('create research project'),
        'type'              => MENU_CALLBACK,
    );
    $menu['project/%/manage/message/templates/view/%'] = array(
        'title'             => t('Message template'),
        'description'       => t('View message template'),
        'page callback'     => 'project_manage_message_templates_view_callback',
        'page arguments'    => array(1, 6),
        'access arguments'  => array('create research project'),
        'type'              => MENU_CALLBACK,
    );
    $menu['project/%/manage/message/templates/edit/%'] = array(
        'title'             => t('Edit message template'),
        'description'       => t('Edit the message template'),
        'page callback'     => 'project_manage_message_templates_edit_callback',
        'page arguments'    => array(1, 6),
        'access arguments'  => array('create research project'),
        'type'              => MENU_CALLBACK,
    );
    $menu['project/%/manage/message/templates/delete/%'] = array(
        'title'             => t('DELETE message template'),
        'description'       => t('DELETE the message template'),
        'page callback'     => 'project_manage_message_templates_delete_callback',
        'page arguments'    => array(1, 6),
        'access arguments'  => array('create research project'),
        'type'              => MENU_CALLBACK,
    );
    return $menu;
}

/**
 * Menu callback for project/%/manage/message/templates
 */
function project_manage_message_templates_callback($path){
    //get project id
    $project = load_project($path);
    if($project){
        
        $content = '';
        $rows = array();
        $header = array(
            array('data'=>'Title'),
            array('data'=>'Type'),
            array('data'=>'Abstract'),
        );
        
        //get templates
        $sql = "SELECT id,  project, type, title, content FROM  {project_message_templates} WHERE project=%d ORDER BY created DESC";
        $res = pager_query($sql, 30, 0, $project->id);
        
        while($row = db_fetch_object($res)){
            $rows[] = array(
                l($row->title, 'project/'.$path.'/manage/message/templates/edit/'.$row->id),
                $row->type,
                l(node_teaser($row->content, null, 600), 'project/'.$path.'/manage/message/templates/edit/'.$row->id),
            );
        }
    
        $content.= theme_table($header, $rows);
        $content.= theme('pager');
    
        return $content;
        
    }else{
        drupal_not_found();
    }
}

/**
 * Menu callback for project/%/manage/message/templates/add
 */
function project_manage_message_templates_add_callback($path){
    //get project id
    $project = load_project($path);
    if($project){
        $template = new stdClass;
        $template->project = $project->id;
        return drupal_get_form('project_message_template_form', $template);
    }else{
        drupal_not_found();
    }
    
}

/**
 * Menu callback for project/%/manage/message/templates/view/%
 */
function project_manage_message_templates_view_callback($path, $tpl_id){
    $sql = "SELECT id,  project, type, title, content FROM  {project_message_templates} WHERE id=%d";
    $tpl = db_fetch_object($sql, $tpl_id);
    
}

/**
 * Menu callback for project/%/manage/message/templates/edit/%
 */
function project_manage_message_templates_edit_callback($path, $tpl_id){
    //get template info
    $sql = "SELECT id,  project, type, title, content FROM  {project_message_templates} WHERE id=%d";
    $tpl = db_fetch_object($sql, $tpl_id);
    return drupal_get_form('project_message_template_form', $tpl);
}

/**
 * Menu callback for project/%/manage/message/templates/delete/%
 */
function project_manage_message_templates_delete_callback($path, $tpl_id){
    
}

/** message template form **/
function project_message_template_form(&$form_state, $mTemplate=NULL){
    $form['id'] = array(
        '#type'         => 'hidden',
        '#value'        => isset($mTemplate->id)?$mTemplate->id:0,
    );
    $form['project'] = array(
        '#type'         => 'hidden',
        '#value'        => isset($mTemplate->project)?$mTemplate->project:0,
    );
    $options = array('email' => t('For email'), 'sms' => t('For SMS'));
    $form['type'] = array(
        '#type'         => 'radios',
        '#title'        => t('Template type'),
        '#default_value'=> isset($mTemplate->type)?$mTemplate->type:'email',
        '#options'      => $options,
        '#required'     => TRUE,
    );
    $form['title'] = array(
        '#type'         => 'textfield',
        '#title'        => t('Title'),
        '#default_value'=> isset($mTemplate->title)?$mTemplate->title:'',
        '#required'     => TRUE,
    );
    $form['content'] = array(
        '#type'         => 'textarea',
        '#title'        => t('Content'),
        '#default_value'=> isset($mTemplate->content)?$mTemplate->content:'',
        '#required'     => TRUE,
    );
    $form['submit'] = array(
        '#type'         => 'submit',
        '#value'        => t('Save'),
    );
    return $form;
}

function project_message_template_form_submit($form, &$form_state){
    $id = (int)$form_state['values']['id'];
    $project = $form_state['values']['project'];
    $type = $form_state['values']['type'];
    $title = $form_state['values']['title'];
    $content = $form_state['values']['content'];
    
    if($id>0){
        //update
        $update = "UPDATE {project_message_templates} SET project=%d, type='%s', title='%s', content='%s', changed=NOW() WHERE id=%d";
        db_query($update, $project, $type, $title, $content, $id);
    }else{
        //insert
        $insert = "INSERT INTO {project_message_templates} (project, type, title, content, created, changed) VALUES(%d, '%s', '%s', '%s', NOW(), NOW())";
        db_query($insert, $project, $type, $title, $content);
    }
    
    drupal_goto(get_project_url($project).'/manage/message/templates');
    
}
/** message teplate delete form **/
function project_message_template_delete_form(&$form_state, $mTemplate=NULL){
    
}
function project_message_template_delete_form_submit($form, &$form_state){
    
}