<?php

/**
 * @file
 * Support separate user profile page, overwrite user page.
 */

/**
 * Implementation of hook_menu().
 */
function reProjectUserProfile_menu(){
    $menu['user/%user/edit/personal_info'] = array(
        'title' => t('Personal information'),
        'description'       => t('Display edit personal information form. '),
        'page callback'     => 'user_edit_personal_info_callback',
        'page arguments'    => array(1, 'user'),
        'access callback'  => 'edit_personal_info_access',
        'access arguments' => array(1, 'user'),
        'file'              => 'personal_info.page.inc',
        'type'              => MENU_LOCAL_TASK,
    );
    $menu['user/%user/ajax/personal_info'] = array(
        'title' => t('Personal information'),
        'description'       => t('Return personal information as json. '),
        'page callback'     => 'user_ajax_personal_info_callback',
        'page arguments'    => array(1, 'user'),
        'access arguments' => array('access content'),
        'file'              => 'personal_info.ajax.inc',
        'type'              => MENU_CALLBACK,
    );
    return $menu;
}

/**
 * Implementation of hook_perm()
 */
function reProjectUserProfile_perm(){
    return array(
        'view any user project profile',
        'edit any user project profile',
        'view other users projects',
    );    
}

/**
 * Implementation of hook_user().
 */
function reProjectUserProfile_user($op, &$edit, &$account, $category = NULL){
    global $user;
    if($op=='view'){
        if(edit_personal_info_access($account)){
            
            //get profile info
            $info = load_user_personal_info($account->uid);
            $account->content['personal_info'] = array(
                '#title'    => t('Personal information'),
                '#type'    => 'user_profile_category',
                '#weight' => 0,
                'email_address' => array(
                    '#title' => t('Email'),
                    '#type' =>  'user_profile_item',
                    '#value' => $account->mail,
                    '#weight' => -9,
                ),
                'real_name' => array(
                    '#title' => t('Real name'),
                    '#type' =>  'user_profile_item',
                    '#value' => (empty($info->firstname)&&empty($info->lastname))?'Anonymous':$info->firstname.' '.$info->lastname,
                    '#weight' => -10,
                ),
                'age' => array(
                    '#title' => t('Age'),
                    '#type' =>  'user_profile_item',
                    '#value' => empty($info->age)?t('Unknown'):$info->age,
                    '#weight' => 1,
                ),
                'gender' => array(
                    '#title' => t('Gender'),
                    '#type' =>  'user_profile_item',
                    '#value' => ($info->gender=='f')?t('Female'):(($info->gender=='m')?'Male':'Secret'),
                    '#weight' => 1,
                ),
                'height' => array(
                    '#title' => t('Height'),
                    '#type' =>  'user_profile_item',
                    '#value' => empty($info->height)?t('Unknown'):$info->height.' CM',
                    '#weight' => 10,
                ),
                'weight' => array(
                    '#title' => t('Body weight'),
                    '#type' =>  'user_profile_item',
                    '#value' => empty($info->weight)?t('Unknown'):$info->weight.' KG',
                    '#weight' => 10,
                ),
            ); 
            
        }
        if(($user->uid==$account->uid)||user_access("view other users projects")){
            if(user_access('create research project')){
                $create_link= '<p style=""><a href="'.url('projects/new').'" class="add_link">Create new project</a></p>';
            }
            $account->content['projects'] = array(
                '#title'    => t('Projects'),
                '#type'    => 'user_profile_category',
                '#weight' => -1,
                'create_link' => array(
                  '#value' => $create_link,
                  '#weight'=> -1,
                ),
            );
            
            //get research projects list
            $research_p_sql = 'SELECT name, path '
                             .'FROM {research_projects_persons_list} AS p, '
                             .'{research_projects} AS r '
                             .'WHERE user=%d AND p.role IN ("creator","researcher") AND p.active=1 AND p.project=r.id '
                             .'ORDER BY p.changed DESC';
            $rp_res = db_query($research_p_sql, $account->uid);
            while($rp_r = db_fetch_object($rp_res)){
                $research_projects.='<li>'.l($rp_r->name, 'project/'.$rp_r->path).' ['.l(t('manage'), 'project/'.$rp_r->path.'/manage').']</li>'; 
            }
            if(!empty ($research_projects)){
                $account->content['projects']['research_projects'] = array(
                    '#title' => t('Research'),
                    '#type' =>  'user_profile_item',
                    '#value' => empty ($research_projects)?'':"<ul>$research_projects</ul>",
                    '#weight' => 1,
                );
            }
            //get participate in projects list
            $participate_p_sql = 'SELECT name, path '
                             .'FROM {research_projects_persons_list} AS p, '
                             .'{research_projects} AS r '
                             .'WHERE user=%d AND p.role="participant" AND p.active=1 AND p.project=r.id '
                             .'ORDER BY p.changed DESC';
            $pp_res = db_query($participate_p_sql, $account->uid);
            while($pp_r = db_fetch_object($pp_res)){
                $participate_projects.='<li>'.l($pp_r->name, 'project/'.$pp_r->path).'</li>'; 
            }
            if(!empty($participate_projects)){
                $account->content['projects']['participate_projects'] = array(
                    '#title' => t('Participate'),
                    '#type' =>  'user_profile_item',
                    '#value' => empty ($participate_projects)?'':"<ul>$participate_projects</ul>",
                    '#weight' => 2,
                );
            }
        }
    }elseif($op=='load'){
        if(view_personl_info_access($account)){
            $account->profile_info = load_user_personal_info($account->uid);
        }
    }
}

/**
 * Implementation of hook_project_participant_card_info().
 */
function reProjectUserProfile_project_participant_card_info($pid, $uid){
    if($uid>0){
        $info = load_user_personal_info($uid);
        
        $card['gender'] = array(
            'name' => t('Gender'),
            'value'=> ($info->gender=='f')?t('Female'):(($info->gender=='m')?'Male':'Secret'),
            'weight' => 0,
        );
        $card['age'] = array(
            'name' => t('Age'),
            'value'=> empty($info->age)?t('Unknow'):$info->age,
            'weight' => 0,
        );
    }
    return $card;
    
}

/**
 * Access callback for checking if current user has the permission to edit the profile
 */
function edit_personal_info_access($u){
    global $user;
    if($user->status>0 && $user->uid==$u->uid){
        return TRUE;
    }elseif(user_access('edit any user project profile')){
        return TRUE;
    }
    return FALSE;
}

/**
 * Access callback for view user profile
 */
function view_personl_info_access($u){
    global $user;
    if($user->status>0 && $user->uid==$u->uid){
        return TRUE;
    }elseif(user_access('view any user project profile')){
        return TRUE;
    }elseif(user_can_be_studied($u->uid)){
        return TRUE;
    }
    return FALSE;
}

/****************** module function ******************/
/**
 * Get user personal infor, return object
 * @param
 *    $uid, the id fo user
 * @return
 *    Object|FALSE
 */
function load_user_personal_info($uid){
    $check = 'SELECT COUNT(uid) FROM {users} WHERE uid=%d';
    if($uid>0 && db_result(db_query($check, $uid))>0){
        $sql = 'SELECT user, firstname, lastname, gender, birthday, IF(birthday="", "", ((YEAR(CURDATE())-YEAR(birthday))-(RIGHT(CURDATE(),5)<RIGHT(birthday,5)))) AS age, weight, height FROM {research_project_user_profile} WHERE user=%d';
        $info = db_fetch_object(db_query($sql, $uid));
        if(!$info){
            //insert new
            $insert = 'INSERT INTO {research_project_user_profile}  (user, created, changed) '
                      .'VALUES(%d, NOW(), NOW())';
            db_query($insert, $uid);
            $info = new stdClass;
            $info->user = $uid;
        }
        return $info;
    }           
    return FALSE;
}

